version: '3.8'

services:
  php-apache:
    container_name: php-apache
    build:
      context: ./docker/php
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf